stages:
  - build
  - deploy

build_on_gitlab:
  stage: other
  image: docker:latest
  services:
  - docker:dind
  stage: build
  script:
    - docker-compose build
    - docker-compose
    - docker push registry.gitlab.com/mjkochell/music-sniper-rails:latest

build_to_heroku:
  stage: build
  image: docker:latest
  services:
  - docker:dind
  before_script:
    - apk add bash
    - apk add curl
    - apk add nodejs
    - curl https://cli-assets.heroku.com/install.sh | sh
  script:
    - docker login --username=_ --password=$(heroku auth:token) registry.heroku.com
    - heroku container:push web

deploy_to_heroku:
  stage: deploy
  image: docker:latest
  services:
  - docker:dind
  dependencies:
    - build_to_heroku
  script:
    - heroku container:login
    - heroku container:release web
